import crypto from "crypto";
import { Octokit } from "@octokit/rest";
import { createAppAuth } from "@octokit/auth-app";

export function getHeader(headers = {}, name) {
  const match = Object.keys(headers).find((key) => key.toLowerCase() === name.toLowerCase());
  return match ? headers[match] : undefined;
}

function getPrivateKey() {
  return (process.env.PRIVATE_KEY || "").replace(/\\n/g, "\n");
}

export function createGitHubClient(installationId) {
  return new Octokit({
    authStrategy: createAppAuth,
    auth: {
      appId: process.env.APP_ID,
      privateKey: getPrivateKey(),
      installationId,
    },
  });
}

export function verifyWebhookSignature({ headers, bodyRaw, body, secret = process.env.WEBHOOK_SECRET }) {
  if (!secret) return false;

  const signature = getHeader(headers, "x-hub-signature-256");
  if (!signature || typeof signature !== "string") return false;

  const payload =
    typeof bodyRaw === "string" || Buffer.isBuffer(bodyRaw)
      ? bodyRaw
      : typeof body?.bodyText === "string"
        ? body.bodyText
      : typeof body === "string"
        ? body
        : JSON.stringify(body || {});

  const digest = `sha256=${crypto.createHmac("sha256", secret).update(payload).digest("hex")}`;
  const digestBuffer = Buffer.from(digest);
  const signatureBuffer = Buffer.from(signature);

  if (digestBuffer.length !== signatureBuffer.length) return false;
  return crypto.timingSafeEqual(digestBuffer, signatureBuffer);
}

export async function fetchPrDiff(pr) {
  if (!pr?.diff_url) return "No diff available";

  const response = await fetch(pr.diff_url, {
    headers: {
      Accept: "application/vnd.github.v3.diff",
      "User-Agent": "appwrite-github-ai-agent",
    },
  });

  if (!response.ok) {
    throw new Error(`Diff fetch failed with status ${response.status}`);
  }

  return response.text();
}

function formatReviewComment(issue) {
  return `🚨 **${String(issue.severity || "low").toUpperCase()} | ${String(issue.type || "best-practice").toUpperCase()}**

📌 **${issue.title || "Review note"}**

🧠 **Problem**
${issue.explanation || "No explanation returned."}

⚡ **Impact**
${issue.impact || "No impact returned."}

💡 **Fix**
${issue.suggestion || "No suggestion returned."}

🛠 **Example**
\`\`\`
${issue.example_fix || ""}
\`\`\``;
}

export async function createInlineReviewComments({ octokit, repo, pr, issues, logger = console.log }) {
  for (const issue of issues || []) {
    if (!issue?.file || !issue?.line) continue;

    try {
      await octokit.pulls.createReviewComment({
        owner: repo.owner.login,
        repo: repo.name,
        pull_number: pr.number,
        body: formatReviewComment(issue),
        commit_id: pr.head.sha,
        path: issue.file,
        line: Number(issue.line),
      });
    } catch (err) {
      logger(`Inline comment failed: ${err.message}`);
    }
  }
}

export async function applyReviewLabels({ octokit, repo, pr, hasHigh, hasMedium, logger = console.log }) {
  const labels = hasHigh
    ? ["🚨 high-risk", "needs-fix"]
    : hasMedium
      ? ["⚠️ needs-review"]
      : ["✅ safe"];

  try {
    await octokit.issues.addLabels({
      owner: repo.owner.login,
      repo: repo.name,
      issue_number: pr.number,
      labels,
    });
  } catch (err) {
    logger(`Label error: ${err.message}`);
  }
}

export async function createCommitStatus({ octokit, repo, pr, hasHigh, logger = console.log }) {
  try {
    await octokit.repos.createCommitStatus({
      owner: repo.owner.login,
      repo: repo.name,
      sha: pr.head.sha,
      state: hasHigh ? "failure" : "success",
      context: "AI Code Review",
      description: hasHigh ? "❌ High severity issues found" : "✅ No critical issues",
    });
  } catch (err) {
    logger(`Status error: ${err.message}`);
  }
}

export async function createSummaryComment({ octokit, repo, pr, review }) {
  await octokit.issues.createComment({
    owner: repo.owner.login,
    repo: repo.name,
    issue_number: pr.number,
    body: `## 🤖 AI PR Review

### 📌 Summary
${review.summary}

### 🧠 Issues Found
${review.issues.length}

### 📊 Code Quality Score
${review.score}/10

### 🚦 Verdict
${review.verdict === "request_changes" ? "❌ Request Changes" : "✅ Approved"}

---

### 🔍 Issue Breakdown
${review.issues.map((issue) => `- ${issue.title} (${issue.severity})`).join("\n")}

> Generated by Advanced AI Reviewer 🚀`,
  });
}

export async function fetchGitHubProfile(username) {
  const userResponse = await fetch(`https://api.github.com/users/${encodeURIComponent(username)}`, {
    headers: {
      Accept: "application/vnd.github+json",
      "User-Agent": "appwrite-github-ai-agent",
    },
  });

  if (!userResponse.ok) {
    throw new Error(`GitHub user fetch failed with status ${userResponse.status}`);
  }

  const repoResponse = await fetch(
    `https://api.github.com/users/${encodeURIComponent(username)}/repos?per_page=5&sort=updated`,
    {
      headers: {
        Accept: "application/vnd.github+json",
        "User-Agent": "appwrite-github-ai-agent",
      },
    }
  );

  if (!repoResponse.ok) {
    throw new Error(`GitHub repos fetch failed with status ${repoResponse.status}`);
  }

  const user = await userResponse.json();
  const repos = await repoResponse.json();
  const reposDetailed = repos.map((repo) => `
    Name: ${repo.name}
    Stars: ${repo.stargazers_count}
    Language: ${repo.language}
    Description: ${repo.description}
    `);

  return {
    username,
    bio: user.bio || "No bio",
    repoCount: user.public_repos,
    repos: repos.map((repo) => repo.name),
    reposDetailed,
  };
}
